backend:
  name: git-gateway
  repo: timdreesen/arztpraxis
  branch: main
  identity_url: https://auth.decapbridge.com/sites/940cdcb2-d106-4fbd-b0e6-552f662fe744
  gateway_url: https://gateway.decapbridge.com

local_backend: true # Set to true to allow connecting to your local site

# ðŸ’¡ Configure the 'dev_server' to point to your local development server's address
dev_server:
  protocol: http
  host: localhost
  port: 3000 # Use the port your local dev server runs on (e.g., 8000 for Gatsby, 3000 for Next.js)

commit_messages:
  create: 'Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge'
  update: 'Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge'
  delete: 'Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge'
  uploadMedia: 'Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge'
  deleteMedia: 'Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge'
  openAuthoring: "Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge"

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

site_url: https://dreesen.info.netlify.app
logo_url: https://dreesen.info/favicon-32x32.png

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "outofoffice"
    label: "Urlaub/Aktuelles"
    folder: "content/ooo"
    extension: "json"
    format: "json"
    create: true
    summary: "Urlaub: {{start_date}} - {{end_date}}"
    slug: "notice-{{year}}-{{month}}-{{day}}"

    fields:
      - label: "Von"
        name: "start_date"
        widget: "datetime"
        date_format: "DD.MM.YY"
        time_format: false

      - label: "Bis"
        name: "end_date"
        widget: "datetime"
        date_format: "DD.MM.YY"
        time_format: false

      - label: "Vertretung"
        name: "available_doctors"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string", required: true }
          - {
              label: "Telefon",
              name: "phone",
              widget: "string",
              required: true,
            }
          - {
              label: "Adresse",
              name: "address",
              widget: "string",
              required: true,
            }
          - {
              label: "Zusatz",
              name: "bonus",
              widget: "string",
              required: false,
            }
        default:
          - {
              name: "Dr. Teske-Hargus",
              phone: "04503/31936",
              address: "Poststr. 34, Tdf. Strand",
            }
          - {
              name: "Dr. Kallien",
              phone: "04503/2559",
              address: "Strandallee 94a, Tdf. Strand",
            }
          - {
              name: "Dr. SchÃ¼tz",
              phone: "04503/4098",
              address: "Bergstr. 2, Tdf. Strand",
            }
          - {
              name: "Dr. Thaler",
              phone: "04503/1260",
              address: "Erlenbruchstr. 3, Tdf. Strand",
            }
          - {
              name: "Dres. Eschweiler",
              phone: "04503/889021",
              address: "Strandstr. 129, Niendorf",
            }

      - label: "Nachricht"
        name: "message"
        widget: "text"
        required: false

      - label: "VerÃ¶ffentlicht"
        name: "published"
        widget: "boolean"
        default: true
